[types]
fix = "ğŸ•"
release = "ğŸš€"
logging = "ğŸ“š"
revert = "ğŸ¤¡"

[scopes]
"app|application|api|core|code" = "ğŸ"
"ui|frontend" = "ğŸ¨"
db = "ğŸ“¦"

[combos.chore]
"lint.*" = "â˜ï¸ğŸ¤“" 
"catch|except.*|error" = "ğŸ¥…"

[combos.feat]
code = "ğŸ‰"
