types:
  fix: "ğŸ•"
  release: "ğŸš€"
  logging: "ğŸ“š"
  revert: "ğŸ¤¡"

# scope keys can be regex patterns
scopes:
  app|application|api|core|code: "ğŸ"
  ui|frontend: "ğŸ¨"
  db: "ğŸ“¦"

combos:
  chore:
    lint.*: "â˜ï¸ğŸ¤“"  # matches lint, linting, linter, etc.
    catch: "ğŸ¥…"
  feat:
    code: "ğŸ‰"
