types:
  fix: "ğŸ•"
  release: "ğŸš€"
  logging: "ğŸ“š"
  catch: "ğŸ¥…"
  security: "ğŸ”’"
  revert: "ğŸ¤¡"

# scope keys can be regex patterns
scopes:
  app|application|api|core|code: "ğŸ"
  lint.*: "â˜ï¸ğŸ¤“"  # matches lint, linting, linter, etc.
  ui: "ğŸ¨"
  db: "ğŸ“¦"
  
